// flow-typed signature: 39bb7696bc2cd0cfe732ed6fc9ddbdcd
// flow-typed version: <<STUB>>/require-context.macro_v^1.0.4/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-context.macro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-context.macro' {
    declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-context.macro/__tests__/require-context.macro.test' {
    declare module.exports: any
}

declare module 'require-context.macro/babel.config' {
    declare module.exports: any
}

declare module 'require-context.macro/context' {
    declare module.exports: any
}

declare module 'require-context.macro/jest.config' {
    declare module.exports: any
}

declare module 'require-context.macro/require-context.macro' {
    declare module.exports: any
}

// Filename aliases
declare module 'require-context.macro/__tests__/require-context.macro.test.js' {
    declare module.exports: $Exports<
        'require-context.macro/__tests__/require-context.macro.test'
    >
}
declare module 'require-context.macro/babel.config.js' {
    declare module.exports: $Exports<'require-context.macro/babel.config'>
}
declare module 'require-context.macro/context.js' {
    declare module.exports: $Exports<'require-context.macro/context'>
}
declare module 'require-context.macro/jest.config.js' {
    declare module.exports: $Exports<'require-context.macro/jest.config'>
}
declare module 'require-context.macro/require-context.macro.js' {
    declare module.exports: $Exports<
        'require-context.macro/require-context.macro'
    >
}
